var ATTRS={
    "小组":["Estaff","V5","八人行","千寻","战狼","Duang"],
    "家乡":["重庆","宁夏","山东","江西","四川","辽宁","安徽","河北","北京","山西","天津","湖北","湖南","新疆","黑龙江"],
    "学校":["北京大学","北京工业大学","北京航空航天大学","北京化工大学","北京交通大学","北京科技大学","北京师范大学","北京外国语大学","北京信息工程学院","北京邮电大学","对外经贸大学","哈尔滨工业大学","黑龙江大学","华中科技大学","吉林大学","济南大学","辽宁工业大学","南京农业大学","南开大学","沈阳理工大学","首都经济贸易大学","西安电子科技大学","浙江大学","中国科学技术大学","中国科学院","中国美术学院","中国农业大学","中国人民大学","中国石油大学","中央财经大学","北京信息科技大学"],
    "部门":["BP&IT","hao123","INF","LBS","ps","SSG-互联网数据研发部","百度百科","百度股市通","百度外卖事业部","财务部","定制化广告产品部","法务部","个人云","国际化产品部","内审部","人力资源部","商务搜索部","商业平台研发部","搜索测试部","移动安全部","移动分发事业部","","移动搜索事业部","用户体验部","预算控制及财务分析部","帐号体系管理部","知识搜索部"]
};

var dataList=[{
        name:"高世钢",
        symbol:"image://./img/default.png",
        attrs:{
            "家乡":2,
            "部门":15,
            "学校":26
        }
    },{
        name:"王文钰",
        symbol:"image://./img/wangwenyu.png",
        attrs:{
            "小组":0,
            "家乡":2,
            "部门":15,
            "学校":7
        }
    },{
        name:"赵振东",
        symbol:"image://./img/zhaozhendong.png",
        attrs:{
            "小组":0,
            "家乡":5,
            "部门":1,
            "学校":19
        }
    },{
        name:"廖佳",
        symbol:"image://./img/liaojia.png",
        attrs:{
            "小组":0,
            "家乡":6,
            "部门":16,
            "学校":9
        }
    },{
        name:"王丹",
        symbol:"image://./img/wangdan.png",
        attrs:{
            "小组":0,
            "家乡":2,
            "部门":18,
            "学校":11
        }
    },{
        name:"张晓栋",
        symbol:"image://./img/zhangxiaodong.png",
        attrs:{
            "小组":0,
            "家乡":2,
            "部门":22,
            "学校":6
        }
    },{
        name:"田振雷",
        symbol:"image://./img/tianzhenlei.png",
        attrs:{
            "小组":0,
            "家乡":10,
            "部门":5,
            "学校":18
        }
    },{
        name:"李静",
        symbol:"image://./img/lijing.png",
        attrs:{
            "小组":0,
            "家乡":3,
            "部门":23,
            "学校":25
        }
    }
    /*v5*/
    ,{
        name:"马小森",
        symbol:"image://./img/maxiaosen.png",
        attrs:{
            "小组":1,
            "家乡":7,
            "部门":14,
            "学校":1
        }
    },{
        name:"李兰",
        symbol:"image://./img/lilan.png",
        attrs:{
            "小组":1,
            "家乡":8,
            "部门":1,
            "学校":20
        }
    },{
        name:"王超",
        symbol:"image://./img/wangchao.png",
        attrs:{
            "小组":1,
            "家乡":9,
            "部门":0,
            "学校":4
        }
    },{
        name:"韩帅",
        symbol:"image://./img/hanshuai.png",
        attrs:{
            "小组":1,
            "家乡":5,
            "部门":2,
            "学校":21
        }
    },{
        name:"邵一峰",
        symbol:"image://./img/shaoyifeng.png",
        attrs:{
            "小组":1,
            "家乡":2,
            "部门":12,
            "学校":17
        }
    },{
        name:"郭少聃",
        symbol:"image://./img/guoshaoran.png",
        attrs:{
            "小组":1,
            "家乡":10,
            "部门":4,
            "学校":13
        }
    },{
        name:"海学森",
        symbol:"image://./img/haixuesen.png",
        attrs:{
            "小组":1,
            "家乡":1,
            "部门":15,
            "学校":27
        }
    }
    /*八人行*/
    ,{
        name:"李妍洁",
        symbol:"image://./img/liyanjie.png",
        attrs:{
            "小组":2,
            "家乡":5,
            "部门":11,
            "学校":3
        }
    },{
        name:"吴佳佳",
        symbol:"image://./img/wujiajia.png",
        attrs:{
            "小组":2,
            "家乡":0,
            "部门":26,
            "学校":13
        }
    },{
        name:"崔代锐",
        symbol:"image://./img/cuidairui.png",
        attrs:{
            "小组":2,
            "家乡":2,
            "部门":8,
            "学校":2
        }
    },{
        name:"李凯",
        symbol:"image://./img/likai.png",
        attrs:{
            "小组":2,
            "家乡":8,
            "部门":14,
            "学校":29
        }
    },{
        name:"王慧玲",
        symbol:"image://./img/wanghuiling.png",
        attrs:{
            "小组":2,
            "家乡":7,
            "部门":18,
            "学校":5
        }
    },{
        name:"张敬民",
        symbol:"image://./img/zhangjingmin.png",
        attrs:{
            "小组":2,
            "家乡":3,
            "部门":13,
            "学校":23
        }
    },{
        name:"白松",
        symbol:"image://./img/baisong.png",
        attrs:{
            "小组":2,
            "家乡":4,
            "部门":4,
            "学校":24
        }
    },{
        name:"李祯",
        symbol:"image://./img/lizhen.png",
        attrs:{
            "小组":2,
            "家乡":7,
            "部门":9,
            "学校":10
        }
    }
    /*千寻*/
    ,{
        name:"付瑶",
        symbol:"image://./img/fuyao.png",
        attrs:{
            "小组":3,
            "家乡":14,
            "部门":9,
            "学校":12
        }
    },{
        name:"郭涛",
        symbol:"image://./img/guotao.png",
        attrs:{
            "小组":3,
            "家乡":12,
            "部门":3,
            "学校":13
        }
    },{
        name:"刘少帅",
        symbol:"image://./img/liushaoshuai.png",
        attrs:{
            "小组":3,
            "家乡":2,
            "部门":20,
            "学校":9
        }
    },{
        name:"王成刚",
        symbol:"image://./img/wangchenggang.png",
        attrs:{
            "小组":3,
            "家乡":13,
            "部门":10,
            "学校":26
        }
    },{
        name:"郭春辉",
        symbol:"image://./img/guochunhui.png",
        attrs:{
            "小组":3,
            "家乡":3,
            "部门":1,
            "学校":5
        }
    },{
        name:"杨一",
        symbol:"image://./img/yangyi.png",
        attrs:{
            "小组":3,
            "家乡":14,
            "部门":2,
            "学校":11
        }
    },{
        name:"岳闻婧",
        symbol:"image://./img/yuewenjing.png",
        attrs:{
            "小组":3,
            "家乡":14,
            "部门":14,
            "学校":19
        }
    }
    /*战狼*/
    ,{
        name:"王宏",
        symbol:"image://./img/wanghong.png",
        attrs:{
            "小组":4,
            "家乡":5,
            "部门":19,
            "学校":16
        }
    },{
        name:"郎咸朋",
        symbol:"image://./img/langxianpeng.png",
        attrs:{
            "小组":4,
            "家乡":2,
            "部门":3,
            "学校":24
        }
    },{
        name:"王学文",
        symbol:"image://./img/wangxuewen.png",
        attrs:{
            "小组":4,
            "家乡":7,
            "部门":14,
            "学校":11
        }
    },{
        name:"白凯",
        symbol:"image://./img/baikai.png",
        attrs:{
            "小组":4,
            "家乡":2,
            "部门":17,
            "学校":2
        }
    },{
        name:"李品",
        symbol:"image://./img/lipin.png",
        attrs:{
            "小组":4,
            "家乡":5,
            "部门":24,
            "学校":27
        }
    },{
        name:"曹璘",
        symbol:"image://./img/caolin.png",
        attrs:{
            "小组":4,
            "家乡":9,
            "部门":25,
            "学校":28
        }
    },{
        name:"邢艳",
        symbol:"image://./img/xingyan.png",
        attrs:{
            "小组":4,
            "家乡":14,
            "部门":4,
            "学校":14
        }
    }
    /*Duang*/
    ,{
        name:"罗琳琳",
        symbol:"image://./img/luolinlin.png",
        attrs:{
            "小组":5,
            "家乡":11,
            "学校":0,
            "部门":15
        }
    },{
        name:"温金超",
        symbol:"image://./img/wenjinchao.png",
        attrs:{
            "小组":5,
            "家乡":10,
            "部门":17,
            "学校":8
        }
    },{
        name:"郑侃",
        symbol:"image://./img/zhengkan.png",
        attrs:{
            "小组":5,
            "家乡":3,
            "部门":12,
            "学校":9
        }
    },{
        name:"张少萌",
        symbol:"image://./img/zhangshaomeng.png",
        attrs:{
            "小组":5,
            "家乡":8,
            "部门":20,
            "学校":30
        }
    },{
        name:"宋海涛",
        symbol:"image://./img/songhaitao.png",
        attrs:{
            "小组":5,
            "家乡":2,
            "部门":26,
            "学校":15
        }
    },{
        name:"袁鹏程",
        symbol:"image://./img/yuanpengcheng.png",
        attrs:{
            "小组":5,
            "家乡":6,
            "部门":5,
            "学校":22
        }
    },{
        name:"熊倩倩",
        symbol:"image://./img/xiongqianqian.png",
        attrs:{
            "小组":5,
            "家乡":7,
            "部门":7,
            "学校":4
        }
    }
];
